from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'base'

urlpatterns = [
    #~ Base del sistema:
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/login.html'), name='logout'),
    #~ Beneficiado :
    path('beneficiado/',
        login_required(views.BeneficiadoList.as_view()),
        name='BeneficiadoList'),
    path('beneficiado/crear',
        login_required(views.BeneficiadoCreate.as_view()),
        name='BeneficiadoCreate'),
    path('beneficiado/detalle/<str:pk>',
        login_required(views.BeneficiadoDetail.as_view()),
        name='BeneficiadoDetail'),
    path('beneficiado/actualizar/<str:pk>',
        login_required(views.BeneficiadoUpdate.as_view()),
        name='BeneficiadoUpdate'),
    path('beneficiado/eliminar/<str:pk>',
        login_required(views.BeneficiadoDelete.as_view()),
        name='BeneficiadoDelete'),
    path('beneficiado/pdf/',
        login_required(views.BeneficiadoPdfList.as_view()),
        name='BeneficiadoPdfList'),
    path('beneficiado/pdf/<str:pk>',
        login_required(views.BeneficiadoPdfUnid.as_view()),
        name='BeneficiadoPdfUnid'),
    path('beneficiado/word/<str:pk>',
        login_required(views.BeneficiadoWord.as_view()),
        name='BeneficiadoWord'),
    path('beneficiado/excel/<str:pk>',
        login_required(views.BeneficiadoExcel.as_view()),
        name='BeneficiadoExcel'),
    #~ Asignar Caja:
    path('asignarcaja/',
        login_required(views.AsignarCajaList.as_view()),
        name='AsignarCajaList'),
    path('asignarcaja/crear',
        login_required(views.AsignarCajaCreate.as_view()),
        name='AsignarCajaCreate'),
    path('asignarcaja/detalle/<str:pk>',
        login_required(views.AsignarCajaDetail.as_view()),
        name='AsignarCajaDetail'),
    path('asignarcaja/actualizar/<str:pk>',
        login_required(views.AsignarCajaUpdate.as_view()),
        name='AsignarCajaUpdate'),
    path('asignarcaja/eliminar/<str:pk>',
        login_required(views.AsignarCajaDelete.as_view()),
        name='AsignarCajaDelete'),
    path('asignarcaja/pdf/',
        login_required(views.AsignarCajaPdfList.as_view()),
        name='AsignarCajaPdfList'),
    #~ Asignar Curso:
    path('asignarcurso/',
        login_required(views.AsignarCursoList.as_view()),
        name='AsignarCursoList'),
    path('asignarcurso/crear',
        login_required(views.AsignarCursoCreate.as_view()),
        name='AsignarCursoCreate'),
    path('asignarcurso/detalle/<str:pk>',
        login_required(views.AsignarCursoDetail.as_view()),
        name='AsignarCursoDetail'),
    path('asignarcurso/actualizar/<str:pk>',
        login_required(views.AsignarCursoUpdate.as_view()),
        name='AsignarCursoUpdate'),
    path('asignarcurso/eliminar/<str:pk>',
        login_required(views.AsignarCursoDelete.as_view()),
        name='AsignarCursoDelete'),
    path('asignarcurso/pdf/',
        login_required(views.AsignarCursoPdfList.as_view()),
        name='AsignarCursoPdfList'),
    #~ Caja:
    path('caja/',
        login_required(views.CajaList.as_view()),
        name='CajaList'),
    path('caja/crear',
        login_required(views.CajaCreate.as_view()),
        name='CajaCreate'),
    path('caja/detalle/<str:pk>',
        login_required(views.CajaDetail.as_view()),
        name='CajaDetail'),
    path('caja/actualizar/<str:pk>',
        login_required(views.CajaUpdate.as_view()),
        name='CajaUpdate'),
    path('caja/eliminar/<str:pk>',
        login_required(views.CajaDelete.as_view()),
        name='CajaDelete'),
    path('caja/pdf/',
        login_required(views.CajaPdfList.as_view()),
        name='CajaPdfList'),
    path('caja/pdf/<str:pk>',
        login_required(views.CajaPdfUnid.as_view()),
        name='CajaPdfUnid'),
    path('caja/word/<str:pk>',
        login_required(views.CajaWord.as_view()),
        name='CajaWord'),
    path('caja/excel/<str:pk>',
        login_required(views.CajaExcel.as_view()),
        name='CajaExcel'),
    #~ Curso:
    path('curso/',
        login_required(views.CursoList.as_view()),
        name='CursoList'),
    path('curso/crear',
        login_required(views.CursoCreate.as_view()),
        name='CursoCreate'),
    path('curso/detalle/<str:pk>',
        login_required(views.CursoDetail.as_view()),
        name='CursoDetail'),
    path('curso/actualizar/<str:pk>',
        login_required(views.CursoUpdate.as_view()),
        name='CursoUpdate'),
    path('curso/eliminar/<str:pk>',
        login_required(views.CursoDelete.as_view()),
        name='CursoDelete'),
    path('curso/pdf/',
        login_required(views.CursoPdfList.as_view()),
        name='CursoPdfList'),
    path('curso/pdf/<str:pk>',
        login_required(views.CursoPdfUnid.as_view()),
        name='CursoPdfUnid'),
    path('curso/word/<str:pk>',
        login_required(views.CursoWord.as_view()),
        name='CursoWord'),
    path('curso/excel/<str:pk>',
        login_required(views.CursoExcel.as_view()),
        name='CursoExcel'),
    #~ Sector:
    path('sector/',
        login_required(views.SectorList.as_view()),
        name='SectorList'),
    path('sector/crear',
        login_required(views.SectorCreate.as_view()),
        name='SectorCreate'),
    path('sector/detalle/<str:pk>',
        login_required(views.SectorDetail.as_view()),
        name='SectorDetail'),
    path('sector/actualizar/<str:pk>',
        login_required(views.SectorUpdate.as_view()),
        name='SectorUpdate'),
    path('sector/eliminar/<str:pk>',
        login_required(views.SectorDelete.as_view()),
        name='SectorDelete'),
    path('sector/pdf/',
        login_required(views.SectorPdfList.as_view()),
        name='SectorPdfList'),
    path('sector/pdf/<str:pk>',
        login_required(views.SectorPdfUnid.as_view()),
        name='SectorPdfUnid'),
    path('sector/word/<str:pk>',
        login_required(views.SectorWord.as_view()),
        name='SectorWord'),
    path('sector/excel/<str:pk>',
        login_required(views.SectorExcel.as_view()),
        name='SectorExcel'),
    #~ Historico de Entrega:
    path('historico/',
        login_required(views.HistoricoEntregaList.as_view()),
        name='HistoricoEntregaList')
]
